# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1


jobs:
  build:
    docker:
<<<<<<< HEAD
      - image: cimg/node:17.2.0
=======
      -image: circleci/node:16.13


>>>>>>> c56d06124560bba41bc2662605f91ddd23f5e0f5
    steps:
      - checkout
      - run: npm test
