version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: circleci/node:8.9.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    executor: my-custom-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test